name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_stars: yes

          theme: dark

          layout: compact

          color: "#FFD700"
