name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_stars: yes

          # Ganti theme/layout lama ke template
          template: classic
          config_presets: github

          # Kalau mau custom warna (ganti theme/color lama)
          extras_css: |
            :root {
              --color-calendar-graph-day-bg: #161B22;
              --color-calendar-graph-day-L1-bg: #FFD700; # emas
              --color-calendar-graph-day-L2-bg: #DAA520;
              --color-calendar-graph-day-L3-bg: #B8860B;
              --color-calendar-graph-day-L4-bg: #8B7500;
            }
